name = "ECC"
uuid = "a99b485a-c5c8-540e-ab00-7a7265134077"
keywords = ["cryptography"]
license = "MIT"
authors = ["roshii <admin@brane.cc>"]
description = "Elliptic Curve Cryptography"
repository = "https://gitlab.com/braneproject/ECC.jl.git"
version = "0.2.3"

[compat]
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
